### ISSUE TITLE
Add SIC codes - aka industry_code_uids fields - from OpenCorporates bulk data to Elasticsearch

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/register-ingester-oc#19]
As part of upcoming data analysis efforts, Open Ownership would like to store the industry_code_uids fields that we get from OpenCorporates' bulk data in Elasticsearch to support data analysis efforts looking across certain markets.

These are the fields currently used are listed at https://github.com/openownership/register-ingester-oc/blob/main/lib/register_ingester_oc/companies/create_tables_service.rb#L83

The SIC codes are in the bulk data here:
https://github.com/openownership/register-ingester-oc/blob/main/lib/register_ingester_oc/companies/create_tables_service.rb#L158

To add a new field, we should add that column to the ones being ingested and ensure it is indexed appropriately in Elasticsearch

**Comment by StephenAbbott** [comment]
SIC codes = what are used in UK and USA. NACE codes are used across Europe. Check what coverage OpenCorporates has

**Comment by tiredpixel** [comment]
So, `industry_code_uids` is indeed present, but there is no specific mention of SIC or NACE codes with the header.

However, an example of a cell within this column in the data is:

```
be_nace_2008-30300|be_nace_2008-3030|be_nace_2008-303|be_nace_2008-30|eu_nace_2-3030|isic_4-3030|eu_nace_2-303|isic_4-303|eu_nace_2-30|isic_4-30|eu_nace_2-C|isic_4-C|be_nace_2008-46751|be_nace_2008-4675|be_nace_2008-467|be_nace_2008-46|eu_nace_2-4675|isic_4-4669|eu_nace_2-467|isic_4-466|eu_nace_2-46|isic_4-46|eu_nace_2-G|isic_4-G
```

So it appears that multiple SIC and NACE codes are listed in a pipe-separated format.

It's not clear to me whether to parse these codes, e.g. `isic_4-303` or `eu_nace_2-303` any further, though, and if so, how that should happen.

I'm also not sure about the difference between prefixes like `be_nace` and `eu_nace`, but the entity used as an example there was from Belgium, so perhaps `eu` is EU NACE codes, `isic` SIC codes (are ISIC and SIC the same?), and other codes are country codes?

Looking at a specific example, BE 0672406374:

```
be_nace_2008-46211|be_nace_2008-4621|be_nace_2008-462|be_nace_2008-46|eu_nace_2-4621|isic_4-4620|eu_nace_2-462|isic_4-462|eu_nace_2-46|isic_4-46|eu_nace_2-G|isic_4-G
```

This has a number of codes, including `be_nace_2008-46211`. Checking OpenCorporates:
https://opencorporates.com/companies/be/0672406374

This lists only a single industry code, Code Scheme `NACE-BEL 2008`, Code `46211`. That would imply that the part before the hyphen is the scheme, and the part after the code. In this case, I'm not sure why all the other codes aren't listed on the OpenCorporates page, however.

**Comment by tiredpixel** [comment]
Note that the production Athena database used in this ingestion appears to be `open_corporates`, *not* `open_corporates_prod`.

Also, it appears to be necessary to extend the Athena tables, since `industry_code_uids` is dropped before the `ingest-into-es` or `export-oc-data` stages. Thus, it appears necessary to extend the following areas:

- [ ] lib/register_ingester_oc/companies/create_tables_service.rb
- [ ] lib/register_ingester_oc/companies/conversion_service.rb
- [ ] lib/register_ingester_oc/companies/exporter_service.rb
- [ ] lib/register_ingester_oc/companies/row_processor.rb

**Comment by tiredpixel** [comment]
Doing this work also requires extending the locked-down IAM permissions, to establish a minimal profile which is safe for development. This is complicated by the fact that the code does not appear to respect the `ATHENA_DATABASE` setting.

**Comment by tiredpixel** [comment]
Industry code UIDS, e.g. SIC or NACE, are now integrated into the OpenCorporates Companies data imports, and made available in Elasticsearch via the `companies` table in the `industry_code_uids` field. This should be populated during the next monthly bulk data import.

It was found during this work that the environment variable `ATHENA_DATABASE` isn't respected, despite being set in production. This has led to the `default` Athena database being used, rather than the `open_corporates` database (or indeed the `open_corporates_prod` database, also present in Athena but seemingly unused). This bug has been filed:
https://github.com/openownership/register/issues/261

The `register-dev` IAM policy was extended as part of this, to allow select access to Athena tables during development. This has been done so as to allow read-only access to monthly bulk data imports, but to segregate read-write data using suffixes. The implementation of this feels rather convoluted; however, it should be relatively safe, and is a lot stricter than what we had before when everything was developed using a single policy.
